### ISSUE TITLE
Would you submit this to package control?

### ISSUE THREAD

**Issue by reagle** [scott-s-douglas/Straighten-Quotes#1]
Straighten-Quotes is no longer in package control. (It look likes the bitbucket repo is 404 and DirectPartners, the maintainer, was purchased.) Would you be willing to package and [submit](https://packagecontrol.io/docs/submitting_a_package) this version?

**Comment by scott-s-douglas** [comment]
Yes, I'd be happy to. I'd neglected to keep track of the package's hosting. I'll submit as soon as I address all open issues.

**Comment by reagle** [comment]
Thanks!

**Comment by reagle** [comment]
This isn't in package control presently.
