### ISSUE TITLE
multicharReplacements not working

### ISSUE THREAD

**Issue by reagle** [scott-s-douglas/Straighten-Quotes#2]
I installed this as a github repository and the multicharReplacements don't work. It'll straighten quotes, but not replace ellipses and n/m-dashes.

**Comment by scott-s-douglas** [comment]
Works On My Machine™ but I'll investigate further.

**Comment by reagle** [comment]
The code is simple, and I'm not sure why it wouldn't work, but it's not. If I can do any debugging/diagnostics, let me know.

**Comment by scott-s-douglas** [comment]
Could you attach a copy of a document where the conversion fails, and tell me your OS+version number? I'm wondering if it's something platform-specific.

**Comment by reagle** [comment]
Weird, it's working today! I'll close for now.
